name: Azure_RG_VM
on: [push]

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Log in with Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  - name: Create a resource group in azure
    run: az group create -l eastus -n My_RG
      
  - name: Create a virtual machine in azure
    run: az vm create -g My_RG -n My_VM --image UbuntuLTS --admin-username myname --admin-password myname -l eastus

